"""
Django settings for carehub_be project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import datetime
import os
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6&1@chxt)6m9*p1%$k48%i5^)vbd1hpl&9dlv3t$(gnp$w5y%c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = "smtp.mailtrap.io"
# EMAIL_HOST_USER = "xxx"
# EMAIL_HOST_PASSWORD = "xxx"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'no-reply@carehub.test'

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'agenda',
    'auditing',
    'billing',
    'patients',
    'invoices',
    'offices',
    'prescriptions',
    'subscriptions',
    'user_settings',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=7),
    'BLACKLIST_AFTER_ROTATION': True,
    'ROTATE_REFRESH_TOKENS': True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

FRONTEND_URL = "http://localhost:5173"
SUBSCRIPTION_TRIAL_DAYS = 0
SUBSCRIPTION_PRORATION_BEHAVIOR = "create_prorations"
STRIPE_SECRET_KEY = "sk_test_51Rw3PpCOd5c3tDTyFIn0WvEmo44wYUjJyZN1M7fl6jxS6AQBrKEune7XRFRIF5y4Rms6fn9QARuiar24wq7GtfSC00665uY2zx"

STRIPE_ROLE_PRICES = {
    "secretary":  "price_1RwlurCOd5c3tDTyG4iwlFCt",
    "practitioner": "price_1RwludCOd5c3tDTyqfAYOdJO",
    "manager": "price_1RwluDCOd5c3tDTyIIDb7r5L",
}

STRIPE_WEBHOOK_SECRET = "whsec_0c32d3a283b6892eb43f59eb7b8ce9ebd3dd6912f5b7c39d07ecfe22236a804c"

AUTH_USER_MODEL = 'accounts.User'
DATA_RETENTION_YEARS = 30

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    "subscriptions.middleware.SubscriptionGateMiddleware",
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditing.middleware.RequestContextMiddleware',
]

CORS_ALLOWED_ORIGINS = ["http://localhost:5173"]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-office-id",
    "authorization",
    "content-type",
]
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173"]

ROOT_URLCONF = 'carehub_be.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'carehub_be.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'carehub_db',
        'USER': 'carehub_user',
        'PASSWORD': '28469',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
