# Generated by Django 5.2.1 on 2025-05-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bce_number', models.CharField(max_length=50, unique=True)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('box', models.CharField(blank=True, max_length=10, null=True)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
